import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next 1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className='cursor-pointer border rounded w-80px text-center py-1 border border-gray-400  hover:(animate-pulse) m-8'>
          Hi...
        </div>
        <div className='border rounded w-80px text-center py-1 border border-gray-400 transition-shadow hover:(animate-pulse shadow shadow-black transition-colors) m-8'>
          Heyy...
        </div>

      </main>
     
    </div>
  )
}
